version: '2'
services:
  ticker:
    build: ./ticker
  ticker0:
    build: ./ticker0
  broadcaster:
    build: ./broadcaster
    ports:
      - "3003:3003"
  zmq-proxy:
    build: ./zmq-proxy
    ports:
      - "3000:3000"
      - "3001:3001"
  logger:
    build: ./my-app
