version: '2'
services:
  ticker-petr4:
    build: ./ticker-petr4
  ticker-vale5:
    build: ./ticker-vale5
  broadcaster:
    build: ./broadcaster
    ports:
      - "3003:3003"
  zmq-proxy:
    build: ./zmq-proxy
    ports:
      - "3000:3000"
      - "3001:3001"
  logger:
    build: ./my-app
