version: '2'
services:
  ticker:
    build: ./ticker
    ports:
      - "3000:3000"
  broadcaster:
    build: ./broadcaster
    ports:
      - "3002:3002"
  zmq-device:
    build: ./zmq-device
    ports:
      - "3001:3001"
  logger:
    build: ./my-app
