version: '2'
services:
  haproxy:
    build: ./haproxy
    ports:
      - "1936:1936"
      - "5001:5001"
      - "5002:5002"
  # java-ticker-petr4:
  #   build: ./java-ticker
  #   env_file:
  #     - ./java-ticker/envs/petr4.env
  # java-ticker-vale5:
  #   build: ./java-ticker
  #   env_file:
  #     - ./java-ticker/envs/vale5.env
  fabric3-ticker-petr4:
    build: ./fabric3-components
    env_file:
      - ./fabric3-components/envs/petr4.env
    entrypoint: java -jar server_producer/target/image/bin/server.jar
  zmq-proxy-0:
    build: ./zmq-proxy
    env_file:
      - ./zmq-proxy/envs/proxy0.env
    ports:
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
  zmq-proxy-1:
    build: ./zmq-proxy
    env_file:
      - ./zmq-proxy/envs/proxy1.env
    ports:
      - "3011:3011"
      - "3012:3012"
      - "3013:3013"
  broadcaster-generic:
    build: ./broadcaster
    ports:
      - "4003:4003"
    env_file:
      - ./broadcaster/envs/generic.env
  broadcaster-petr4:
    build: ./broadcaster
    ports:
      - "4004:4004"
    env_file:
      - ./broadcaster/envs/petr4.env
  broadcaster-vale5:
    build: ./broadcaster
    ports:
      - "4005:4005"
    env_file:
      - ./broadcaster/envs/vale5.env
