version: '2'
services:
  producer-server:
    build:
      context: .
    image: producer-server
    ports:
      - "5001:5001"
    entrypoint: java -jar server_producer/target/image/bin/server.jar clean
    env_file:
      - ./envs/petr4_producer.env
  consumer-server:
    build:
      context: .
    image: consumer-server
    entrypoint: java -jar server_consumer/target/image/bin/server.jar clean
    env_file:
      - ./envs/consumer.env